version: '3.4'

x-envvars: &env
  # AWS_ACCESS_KEY
  MINIO_ROOT_USER: V5NSAQUNLNZ5AP7VLLS6
  # AWS_SECRET_KEY
  MINIO_ROOT_PASSWORD: bu0K3n0kEag8GKfckKPBg4Vu8O8EuYu2UO/wNfqI

services:
  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    entrypoint: sh
    command: -c 'mkdir -p /data/public && /usr/bin/minio server /data --console-address ":9001"'
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      <<: *env
  mc:
    image: minio/mc:RELEASE.2024-03-13T23-51-57Z
    volumes:
      - .:/localdir
    entrypoint: /bin/sh
    # This automatically set the public bucket as public on startup and sync example_data to it
    # We also create a 'private' bucket that will require doing signed requests with the aws
    # access and secret key above
    command: -c "
      mc config host add minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
      mc mb -p minio/public &&
      mc mb -p minio/private &&
      mc anonymous set download minio/public &&
      mc mirror /localdir/example_data/ minio/public/ &&
      mc mirror /localdir/example_data/ minio/private/ "
    depends_on:
      - minio
    environment:
      <<: *env
      FOOBAR: 42

volumes:
  miniodata:
